### ISSUE TITLE
notesDirectory has to be a relative path

### ISSUE THREAD

**Issue by timorunge** [campfighter/terminal-velocity#6]
I was trying to use `~/.notes` as a `notesDirectory` which is not working as expected (I also created the directory manually, changed it to `~/.notes/` etc. pp.).

*Exception:*
`(node:33699) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '~/.notes'
    at Object.mkdirSync (fs.js:775:3)
    at findFiles (/usr/local/lib/node_modules/terminal-velocity/src/modules/library.js:17:8)
    at fromDirectory (/usr/local/lib/node_modules/terminal-velocity/src/modules/library.js:23:27)
    at Object.init (/usr/local/lib/node_modules/terminal-velocity/src/termv.js:10:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/terminal-velocity/bin/termv.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
(node:33699) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33699) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

It's working with the definition of a relative path.

**Comment by campfighter** [comment]
hey @timorunge 

what OS are you running? I'll try to get this replicated and resolved asap. If you find a solution before then feel free to make a PR.

**Comment by timorunge** [comment]
Hey @campfighter,

I'm running MacOS 10.14.2. As shell zsh and everything inside tmux (shell and tmux should not differ). I'll take a look at the code and send a PR if I'll find a solution (but I'm not an nodeJS expert).

**Comment by campfighter** [comment]
Thanks. I'll take a look at it this weekend. Sorry for the issue.

**Comment by campfighter** [comment]
@timorunge 

Alright, this should be resolved now. notesDirectory is now always relative to your home directory. So using a '~' is not required but if you do it should be handled. Here's the commit if you want to take a look 01eea317e08a7bd57a7e39f4748594bbcf2709c8

Try updating to the latest version and see if this solves your issue.
